name: Build And Push Docker Image

on:
  push:
    branches: [ push-to-docker, master ]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./package-lock.json
    - name: create env file
      run: |
        touch .env
        echo REACT_APP_USERNAME=${{ secrets.REACT_APP_USERNAME }} >> .env
        echo REACT_APP_PASSWORD=${{ secrets.REACT_APP_PASSWORD }} >> .env
        echo REACT_APP_NEO4J_URI=${{ secrets.REACT_APP_NEO4J_URI }} >> .env
        echo REACT_APP_NEO4J_USERNAME=${{ secrets.REACT_APP_NEO4J_USERNAME }} >> .env
        echo REACT_APP_NEO4J_PASSWORD=${{ secrets.REACT_APP_NEO4J_PASSWORD }} >> .env
    - run: npm ci
    - run: CI='' npm run build
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/genji-nginx-private:latest
